---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: akentner/rabbitmq-mqtt
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
          ports:
            - containerPort: 15672
            - containerPort: 1883
            - containerPort: 8883

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: ui
      protocol: TCP
      port: 15672
    - name: mqtt
      protocol: TCP
      port: 1883
      nodePort: 31883
    - name: mqtttls
      protocol: TCP
      port: 8883
  type: NodePort
